# Generated by Django 3.0.7 on 2020-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('0', 'to read'), ('1', 'reading'), ('2', 'finished')], default='0', max_length=1),
        ),
    ]
